/home/louues/music/40-Oz_D12.mp3
/home/louues/music/7-Years-Old_Lukas-Graham.mp3
/home/louues/music/A-Horse-With-No-Name_America.mp3
/home/louues/music/Ate-Quando_Gabriel-Pensador.mp3
/home/louues/music/BYOB_System-Of-A-Down.mp3
/home/louues/music/Back-In-Black_ACDC.mp3
/home/louues/music/Bad-To-The-Bone_George-Thorogood.mp3
/home/louues/music/Ballin_Mustard.mp3
/home/louues/music/Because-I-Got-High_Afroman.mp3
/home/louues/music/Big-Poppa_The-Notorious-Big.mp3
/home/louues/music/Black-Betty_Ram-Jam.mp3
/home/louues/music/Black-Vans_Shady.mp3
/home/louues/music/Blinding-Lights_The-Weeknd.mp3
/home/louues/music/Bohemian-Rhapsody_Queen.mp3
/home/louues/music/Bones_Imagine-Dragons.mp3
/home/louues/music/Brasil-De-Quem_Sid.mp3
/home/louues/music/Bubblegum_Hey-Demian.mp3
/home/louues/music/Bunny-Girl_1nonly.mp3
/home/louues/music/Business_Eminem.mp3
/home/louues/music/Can-You-Feel-My-Heart_Bring-Me-The-Horizon.mp3
/home/louues/music/Cant-Feel-My-Face_The-Weeknd.mp3
/home/louues/music/Cant-Help-Falling-In-Love_Elvis-Presley.mp3
/home/louues/music/Carry-On-Wayward-Son_Kansas.mp3
/home/louues/music/Chill-Bill_Rob-Stone.mp3
/home/louues/music/Chop-Suey_System-Of-A-Down.mp3
/home/louues/music/Cleaning-Out-My-Closet_Eminem.mp3
/home/louues/music/Clint-Eastwood_Gorillaz.mp3
/home/louues/music/Cradles_Sub-Urban.mp3
/home/louues/music/Crazy_Gnarls-Barkley.mp3
/home/louues/music/Crocodile-Rock_Elton-John.mp3
/home/louues/music/Death-Bed_Powfu.mp3
/home/louues/music/Dont-Stop-Me-Now_Queen.mp3
/home/louues/music/Drop-It-Like-Its-Hot_Snoop-Dogg.mp3
/home/louues/music/Dust-In-The-Wind_Kansas.mp3
/home/louues/music/Enemy_Imagine-Dragons.mp3
/home/louues/music/Enter-Sandman_Metallica.mp3
/home/louues/music/Eu-Nao-Sou-Racista_Nego-Max.mp3
/home/louues/music/Even-Flow_Pearl-Jam.mp3
/home/louues/music/Everybody-Wants-To-Rule-The-World_Tears-For-Fears.mp3
/home/louues/music/Fear-Of-The-Dark_Iron-Maiden.mp3
/home/louues/music/Fell-Good-Inc_Gorillaz.mp3
/home/louues/music/Fight-Music_D12.mp3
/home/louues/music/Foreste-Caboclo_Legiao-Urbana.mp3
/home/louues/music/Gangorra_Sid.mp3
/home/louues/music/Gangstas-Paradise_Coolio.mp3
/home/louues/music/Ghetto-Waves_Soodope-And-Hersh.mp3
/home/louues/music/Godzilla_Eminem.mp3
/home/louues/music/Golden-Hour_JVKE.mp3
/home/louues/music/Goodbye-Yellow-Brick-Road_Elton-John.mp3
/home/louues/music/Gossip_Maneskin.mp3
/home/louues/music/Goth-Bitch_1nonly.mp3
/home/louues/music/Happy-Together_The-Turtles.mp3
/home/louues/music/Heathens_Twenty-One-Pilots.mp3
/home/louues/music/Hennessey_2pac.mp3
/home/louues/music/Hit-Em-Up_2pac.mp3
/home/louues/music/Hit-The-Road-Jack_Ray-Charles.mp3
/home/louues/music/Hold-The-Line_Toto.mp3
/home/louues/music/Holy-Diver_Dio.mp3
/home/louues/music/Hotel-California_Eagles.mp3
/home/louues/music/House-Of-The-Rising-Sun_The-Animals.mp3
/home/louues/music/Human_Rag-N-Bone-Man.mp3
/home/louues/music/Hypnotize_The-Notorious-Big.mp3
/home/louues/music/I-Wanna-Be-Your-Slave_Maneskin.mp3
/home/louues/music/I-Was-Made-For-Lovin-You_Kiss.mp3
/home/louues/music/Ill-Hurt-You_Busta-Rhymes.mp3
/home/louues/music/Ill-Keep-You-Safe_Sagun.mp3
/home/louues/music/Im-Not-Racist_Joyner-Lucas.mp3
/home/louues/music/Im-Still-Standing_Elton-John.mp3
/home/louues/music/Immigrant-Song_Led-Zeppelin.mp3
/home/louues/music/In-Da-Club_50-Cent.mp3
/home/louues/music/Indios_Legiao-Urbana.mp3
/home/louues/music/Industry-Baby_Lil-Nas-X.mp3
/home/louues/music/It-Was-A-Good-Day_Ice-Cube.mp3
/home/louues/music/Jump-Around_House-Of-Pain.mp3
/home/louues/music/Just-Dont-Give-A-Fuck_Eminem.mp3
/home/louues/music/Just-The-Two-Of-Us_Bill-Withers.mp3
/home/louues/music/Kickapoo_Tenacious-D.mp3
/home/louues/music/Kickback_Nova.mp3
/home/louues/music/Kill-You_Eminem.mp3
/home/louues/music/Killing-In-The-Name_Rage-Against-The-Machine.mp3
/home/louues/music/Ksubi-Jeans_DeeKay.mp3
/home/louues/music/La-Grange_ZZ-Top.mp3
/home/louues/music/Legends-Never-Die_Lol.mp3
/home/louues/music/Life-Goes-On_Oliver-Tree.mp3
/home/louues/music/Like-Toys-Soldiers_Eminem.mp3
/home/louues/music/Limbo_Freddie-Dredd.mp3
/home/louues/music/Little-Dark-Age_MGMT.mp3
/home/louues/music/Lose-Yourself_Eminem.mp3
/home/louues/music/Losing-Interest_Shiloh-Dynasty.mp3
/home/louues/music/Losing-My-Religion_REM.mp3
/home/louues/music/Love-Of-My-Life_Queen.mp3
/home/louues/music/Lovely_Billie-Eilish.mp3
/home/louues/music/Lucid-Dreams_Juice-WRLD.mp3
/home/louues/music/Mammamia_Maneskin.mp3
/home/louues/music/Master-Exploder_Tenacious-D.mp3
/home/louues/music/Master-Of-Puppets_Metallica.mp3
/home/louues/music/Mockingbird_Eminem.mp3
/home/louues/music/Money-Game-part-2_Ren.mp3
/home/louues/music/Mr-Blue-Sky_Elo.mp3
/home/louues/music/My-Band_D12.mp3
/home/louues/music/My-Name-Is_Eminem.mp3
/home/louues/music/Natural_Imagine-Dragons.mp3
/home/louues/music/Not-Afraid_Eminem.mp3
/home/louues/music/Nothing-Else-Matters_Metallica.mp3
/home/louues/music/Numb_Linkin-Park.mp3
/home/louues/music/Old-Town-Road_Lil-Nas-X.mp3
/home/louues/music/Ooh-Ahh_GRITS.mp3
/home/louues/music/Paint-It-Black_The-Rolling-Stones.mp3
/home/louues/music/Pais-E-Filhos_Legiao-Urbana.mp3
/home/louues/music/Paradise_Coldplay.mp3
/home/louues/music/Paranoid_Black-Sabbath.mp3
/home/louues/music/Patriota-Comunista_Gabriel-Pensador.mp3
/home/louues/music/Pimp_50-Cent.mp3
/home/louues/music/Prison-Cell_1voize.mp3
/home/louues/music/Psycho-Killer_Talking-Heads.mp3
/home/louues/music/Pumped-Up-Kicks_Foster-The-People.mp3
/home/louues/music/Pure-Wate_Mustard.mp3
/home/louues/music/Purple-Hills_D12.mp3
/home/louues/music/Radioactive_Imagine-Dragons.mp3
/home/louues/music/Rap-God_Eminem.mp3
/home/louues/music/Riptide_Vance-Joy.mp3
/home/louues/music/Rise_Lol.mp3
/home/louues/music/Rock-Bottom_Eminem.mp3
/home/louues/music/Rocket-Man_Elton-John.mp3
/home/louues/music/Rude_Magic.mp3
/home/louues/music/Run-To-The-Hills_Iron-Maiden.mp3
/home/louues/music/Sambinha_O-Grilo.mp3
/home/louues/music/Save-Your-Tears_The-Weeknd.mp3
/home/louues/music/Serenata-Existencialista_O-Grilo.mp3
/home/louues/music/Shakira_1nonly.mp3
/home/louues/music/Shit-On-You_D12.mp3
/home/louues/music/Sick-Of-U_BoyWithUke.mp3
/home/louues/music/Sing-For-The-Moment_Eminem.mp3
/home/louues/music/Somebody-That-I-Used-To-Know_Gotye.mp3
/home/louues/music/Stairway-To-Heaven_Led-Zeppelin.mp3
/home/louues/music/Stan_Eminem.mp3
/home/louues/music/Stand-By-Me_Ben-E-King.mp3
/home/louues/music/Stand-Up-And-Shout_Dio.mp3
/home/louues/music/Starboy_The-Weeknd.mp3
/home/louues/music/Starman_David-Bowie.mp3
/home/louues/music/Stats_Tae.mp3
/home/louues/music/Stay-With-Me_1nonly.mp3
/home/louues/music/Stay-With-Me_Sam-Smith.mp3
/home/louues/music/Step-Back_1nonly.mp3
/home/louues/music/Still-Dre_Dr-Dre.mp3
/home/louues/music/Still-Loving-You_Scorpions.mp3
/home/louues/music/Stressed-Out_Twenty-One-Pilots.mp3
/home/louues/music/Sunflower_Post-Malone.mp3
/home/louues/music/Superman_Eminem.mp3
/home/louues/music/Sweater-Weather_The-Neighbourhood.mp3
/home/louues/music/Sympathy-For-The-Devil_The-Rolling-Stones.mp3
/home/louues/music/Take-Me-To-Church_Hozier.mp3
/home/louues/music/Tempo-Perdido_Legiao-Urbana.mp3
/home/louues/music/Ten_Hxzz.mp3
/home/louues/music/The-Box_Roddy-Ricch.mp3
/home/louues/music/The-Metal_Tenacious-D.mp3
/home/louues/music/The-Next-Episode_Dr-Dre.mp3
/home/louues/music/The-Number-Of-The-Beast_Iron-Maiden.mp3
/home/louues/music/The-Passanger_Iggy-Pop.mp3
/home/louues/music/The-Real-Slim-Shady_Eminem.mp3
/home/louues/music/The-Search_NF.mp3
/home/louues/music/The-Trooper_Iron-Maiden.mp3
/home/louues/music/The-Way-I-Am_Eminem.mp3
/home/louues/music/The-Winner-Takes-It-All_ABBA.mp3
/home/louues/music/This-Fffire_Franz-Ferdinand.mp3
/home/louues/music/This-Is-America_Childish-Gambino.mp3
/home/louues/music/Thunderstruck_ACDC.mp3
/home/louues/music/Till-I-Collapse_Eminem.mp3
/home/louues/music/To-Feliz-Matei-O-President-2_Gabriel-Pensador.mp3
/home/louues/music/Toxic_BoyWithUke.mp3
/home/louues/music/Toxicity_System-Of-A-Down.mp3
/home/louues/music/Trela_O-Grilo.mp3
/home/louues/music/Tribute_Tenacious-D.mp3
/home/louues/music/Trindade_Lucas-Hype.mp3
/home/louues/music/Trust-Nobody_Sagun.mp3
/home/louues/music/Under-The-Influence_D12.mp3
/home/louues/music/Venom_Eminem.mp3
/home/louues/music/Viva-La-Vida_Coldplay.mp3
/home/louues/music/War-Pigs_Black-Sabbath.mp3
/home/louues/music/Warriors_Lol.mp3
/home/louues/music/Welcome-To-The-Internet_Bo-Burnham.mp3
/home/louues/music/Welcome-To-The-Jungle_Guns-N-Roses.mp3
/home/louues/music/Wellerman_Nathan-Evans.mp3
/home/louues/music/When-Im-Gone_Eminem.mp3
/home/louues/music/White-Room_Cream.mp3
/home/louues/music/Wind-Of-Change_Scorpions.mp3
/home/louues/music/Without-Me_Eminem.mp3
/home/louues/music/Wonderboy_Tenacious-D.mp3
/home/louues/music/Wonderwall_Oasis.mp3
/home/louues/music/Worlds-Smallest-Violin.mp3
/home/louues/music/Write-This-Down_2Pac.mp3
/home/louues/music/You-Know-How-We-Do-It_Ice-Cube.mp3
/home/louues/music/Young-Wild-And-Free_Snoop-Dogg.mp3
